services:
  import-tool-service:
    container_name: import-tool-service
    build:
      context: ./backend/import-tool
      dockerfile: Dockerfile
    ports:
      - "${IMPORT_TOOL_API_PORT}:${IMPORT_TOOL_API_PORT}"
    env_file:
      - ./.env

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${FRONTEND_PORT}:3000"
  #   args:
  #     BUILD_BASE_PATH: cdn
  #   env_file:
  #     - ./frontend/.env
  #   stdin_open: true # -i input flag
  #   tty: true # -t terminal flag
  #   depends_on:
  #     - import-tool-service
