services:
  redis-utilities:
    container_name: redis-utilities
    build:
      context: .
      dockerfile: Dockerfile.hub
    image: redis-utilities-local:latest # built image name
    ports:
      - "${PORT_FRONTEND}:${PORT_FRONTEND}"
      - "${PORT_BACKEND}:${PORT_BACKEND}"
    env_file:
      - ./.env
    stdin_open: true # -i input flag
    tty: true # -t terminal flag
